name: Python Application

# Запускать workflow на каждый push
on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получить код из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Настроить Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Шаг 3: Установить зависимости (если есть requirements.txt)
      # Удалите этот шаг, если нет зависимостей
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      # Шаг 4: Запустить скрипт main.py
      - name: Run Python script
        run: python main.py

